name: Check Full

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: mozilla-actions/sccache-action@v0.0.9
    - uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - run: sudo apt update && sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev file binutils patchelf findutils grep sed coreutils strace zsync
    - run: rustup update stable && rustup default stable
    - run: npm install
    - run: npm run tauri build
    - run: ./appimage/deb_to_appimage.sh
    - uses: actions/upload-artifact@v4
      with:
        name: wayvr_dashboard-x86_64.AppImage
        path: ./appimage/wayvr_dashboard.AppImage*